-- Seed data for Vibecoding Tools

-- Insert categories
INSERT INTO categories (id, label, icon, sort_order) VALUES
  ('all', 'Все', 'Zap', 0),
  ('ide', 'AI IDE', 'Code2', 1),
  ('fullstack', 'Full-stack', 'Layers', 2),
  ('extension', 'Расширения', 'GitBranch', 3),
  ('cli', 'CLI', 'Terminal', 4),
  ('ui', 'UI/Design', 'Palette', 5),
  ('mobile', 'Mobile', 'Smartphone', 6),
  ('agent', 'AI Agents', 'Bot', 7),
  ('assistant', 'Ассистенты', 'Sparkles', 8)
ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

-- Insert tools

-- === AI IDE ===
INSERT INTO tools (id, title, description, category_id, tags, url, pricing, pricing_type, features, llm, open_source, level) VALUES
(
  'cursor',
  'Cursor',
  'AI-powered IDE на базе VS Code. Tab-автокомплит, Composer Mode для многофайловых изменений, фоновые агенты.',
  'ide',
  ARRAY['IDE', 'VS Code', 'Multi-model'],
  'https://cursor.com',
  '$20/мес Pro',
  'freemium',
  ARRAY['Tab-автокомплит с предсказанием', 'Composer Mode для многофайловых изменений', 'Background agents', 'Чат с контекстом всего проекта', 'Privacy Mode'],
  'GPT-4o, Claude 3.5/4, Gemini',
  false,
  'Средний / Продвинутый'
),
(
  'windsurf',
  'Windsurf',
  'AI IDE от Codeium с агентным режимом Cascade и собственной быстрой моделью SWE-1.5.',
  'ide',
  ARRAY['IDE', 'Codeium', 'Agent'],
  'https://windsurf.com',
  '$15/мес Pro',
  'freemium',
  ARRAY['Cascade — агентный режим', 'SWE-1.5 модель (13x быстрее Sonnet)', 'App Deploys на Vercel/AWS', 'Автокомплит 70+ языков'],
  'SWE-1/1.5, Claude, GPT-5',
  false,
  'Начинающий / Средний'
),
(
  'void',
  'Void Editor',
  'Open Source AI IDE. Полный контроль над приватностью, работа с локальными моделями через Ollama.',
  'ide',
  ARRAY['IDE', 'Open Source', 'Privacy'],
  'https://voideditor.com',
  'Бесплатно',
  'free',
  ARRAY['100% бесплатный и open source', 'Любые LLM включая локальные', 'Agent Mode с MCP', 'Checkpoints для отката'],
  'GPT, Claude, Gemini, Ollama',
  true,
  'Средний / Продвинутый'
),
(
  'pearai',
  'PearAI',
  'Open Source AI IDE с интеграцией лучших инструментов: Aider, Supermaven, Continue.',
  'ide',
  ARRAY['IDE', 'Open Source', 'Integrations'],
  'https://trypear.ai',
  'Бесплатно',
  'free',
  ARRAY['AI Chat (Cmd+L)', '@codebase для поиска по проекту', 'Интеграция Aider, Supermaven', 'Автокомплит через Supermaven'],
  'OpenAI, Anthropic, Ollama',
  true,
  'Начинающий / Средний'
),
(
  'continue',
  'Continue.dev',
  'Open Source фреймворк для AI-ассистентов. Mission Control для фоновых агентов.',
  'ide',
  ARRAY['IDE', 'Open Source', 'Framework'],
  'https://continue.dev',
  'Бесплатно',
  'free',
  ARRAY['Chat, Edit, Agent Mode', 'Mission Control для фоновых агентов', 'CLI для автоматизации', 'Интеграция с GitHub, Sentry, Linear'],
  'GPT-4o, Claude 3.5, Codestral, Ollama',
  true,
  'Продвинутый'
),

-- === FULL-STACK ===
(
  'v0',
  'v0 by Vercel',
  'Генерация React/Next.js компонентов из текста. Design Mode, Figma import, GitHub sync.',
  'fullstack',
  ARRAY['UI', 'React', 'Next.js', 'Vercel'],
  'https://v0.dev',
  '$20/мес Premium',
  'freemium',
  ARRAY['Генерация UI из промптов', 'Design Mode', 'Figma import', 'One-click deploy на Vercel'],
  'v0 Agent (собственная модель)',
  false,
  'Начинающий / Средний'
),
(
  'bolt',
  'Bolt.new',
  'Full-stack приложения в браузере. WebContainers + Claude AI для мгновенной разработки.',
  'fullstack',
  ARRAY['Full-stack', 'Browser', 'Supabase'],
  'https://bolt.new',
  '$25/мес Pro',
  'freemium',
  ARRAY['Zero setup — всё в браузере', 'Bolt Cloud для деплоя', 'Supabase интеграция', '1M токенов/мес бесплатно'],
  'Claude AI',
  true,
  'Начинающий / Средний'
),
(
  'lovable',
  'Lovable',
  'Full-stack приложения из промптов. До 20x быстрее традиционной разработки.',
  'fullstack',
  ARRAY['Full-stack', 'No-code', 'Supabase'],
  'https://lovable.dev',
  '$25/мес Pro',
  'freemium',
  ARRAY['Natural language full-stack', 'Lovable Cloud backend', 'Stripe payments интеграция', 'Bidirectional GitHub sync'],
  'Google Gemini, GPT',
  false,
  'Начинающий'
),
(
  'replit',
  'Replit Agent',
  'Cloud IDE + AI Agent. Автоматическое тестирование, reflection loop, instant hosting.',
  'fullstack',
  ARRAY['IDE', 'Cloud', 'Agent'],
  'https://replit.com',
  '$20/мес Core',
  'freemium',
  ARRAY['Agent тестирует свой код', 'Instant hosting', 'Collaboration в реальном времени', 'PostgreSQL интеграция'],
  'Ghostwriter (собственная модель)',
  false,
  'Начинающий'
),
(
  'genkit',
  'Firebase Genkit',
  'Open Source AI Framework от Google. RAG, structured output, tool calling из коробки.',
  'fullstack',
  ARRAY['Framework', 'Google', 'RAG'],
  'https://firebase.google.com/docs/genkit',
  'Бесплатно',
  'free',
  ARRAY['Unified AI model interface', 'RAG из коробки', 'Multimodal support', 'Genkit Developer UI'],
  'Gemini, GPT, Claude, Ollama',
  true,
  'Продвинутый'
),

-- === VS CODE EXTENSIONS ===
(
  'copilot',
  'GitHub Copilot',
  'AI-ассистент от GitHub. Agent mode, code review, PR assist, мультимодельный выбор.',
  'extension',
  ARRAY['VS Code', 'GitHub', 'Multi-model'],
  'https://github.com/features/copilot',
  '$10/мес Pro',
  'freemium',
  ARRAY['Inline completions', 'Copilot Chat', 'Agent mode', 'Code review & PR assist'],
  'GPT-4.1, Claude 3.5 Sonnet, Gemini 2.5 Pro',
  false,
  'Начинающий / Средний / Продвинутый'
),
(
  'codeium',
  'Codeium',
  'Бесплатный unlimited автокомплит. 70+ языков, end-to-end encryption.',
  'extension',
  ARRAY['VS Code', 'Free', '70+ languages'],
  'https://codeium.com',
  'Бесплатно навсегда',
  'free',
  ARRAY['Unlimited автокомплит бесплатно', 'AI Chat', 'Repo search', 'End-to-end encryption'],
  'Собственные модели',
  false,
  'Начинающий / Средний'
),
(
  'tabnine',
  'Tabnine',
  'AI автодополнение с фокусом на приватность. Private deployment, SOC 2, GDPR.',
  'extension',
  ARRAY['VS Code', 'Enterprise', 'Privacy'],
  'https://tabnine.com',
  '$9/мес Dev',
  'paid',
  ARRAY['Private fine-tuning', 'VPC/on-prem deployment', 'SOC 2, GDPR compliance', 'Jira интеграция'],
  'Собственные модели',
  false,
  'Средний / Продвинутый'
),
(
  'amazon-q',
  'Amazon Q Developer',
  'AI Code Assistant с глубокой интеграцией AWS. Java/.NET transformation.',
  'extension',
  ARRAY['VS Code', 'AWS', 'Enterprise'],
  'https://aws.amazon.com/q/developer',
  '$19/мес Pro',
  'freemium',
  ARRAY['Agentic coding', 'Java/.NET transformation', 'Security scans', 'AWS-специфичные запросы'],
  'Claude (через AWS Bedrock)',
  false,
  'Средний / Продвинутый'
),
(
  'cody',
  'Sourcegraph Cody',
  'AI для больших кодовых баз. Deep codebase context, multi-repo search.',
  'extension',
  ARRAY['VS Code', 'Enterprise', 'Multi-repo'],
  'https://sourcegraph.com/cody',
  '$19/мес Enterprise Starter',
  'freemium',
  ARRAY['Deep codebase context', 'Multi-repo search', 'Customizable prompts', 'Self-hosted опция'],
  'Claude 3.5, GPT-4o-mini, Gemini 2.0 Flash',
  false,
  'Продвинутый'
),
(
  'blackbox',
  'Blackbox AI',
  'Autonomous Coding Agent. 300+ AI моделей, code from images (OCR).',
  'extension',
  ARRAY['VS Code', 'Agent', 'OCR'],
  'https://blackbox.ai',
  'Freemium',
  'freemium',
  ARRAY['Autonomous Agent', '300+ AI моделей', 'Code from images (OCR)', 'Desktop Agent'],
  '300+ моделей (OpenAI, Claude и др.)',
  false,
  'Начинающий / Средний'
),

-- === CLI TOOLS ===
(
  'aider',
  'Aider',
  'CLI AI Pair Programming. Git-интеграция с auto-commits, voice-to-code, 100+ языков.',
  'cli',
  ARRAY['CLI', 'Git', 'Open Source'],
  'https://aider.chat',
  'Бесплатно',
  'free',
  ARRAY['Git auto-commits', 'Voice-to-code', 'Maps всего codebase', 'Локальные модели через Ollama'],
  'Claude 3.7 Sonnet, DeepSeek, GPT-4o, Ollama',
  true,
  'Средний / Продвинутый'
),
(
  'claude-code',
  'Claude Code',
  'CLI Agentic Coding от Anthropic. Thinking mode, полный контроль над кодовой базой.',
  'cli',
  ARRAY['CLI', 'Anthropic', 'Agent'],
  'https://claude.ai',
  '$20/мес Pro',
  'paid',
  ARRAY['Agentic coding в терминале', 'Thinking mode', 'File system awareness', 'Terminal commands'],
  'Claude 4.1 Opus, Sonnet 4.5',
  false,
  'Продвинутый'
),
(
  'openhands',
  'OpenHands',
  'Open Source AI Agent Platform. Выполнение любых dev задач: coding, browsing, CLI.',
  'cli',
  ARRAY['CLI', 'Open Source', 'Agent'],
  'https://github.com/OpenHands/OpenHands',
  'Бесплатно',
  'free',
  ARRAY['Универсальный агент', 'Code editing, web browsing, CLI', 'Fleet management', 'Extensible SDK'],
  'Любые модели',
  true,
  'Продвинутый'
),
(
  'gpt-engineer',
  'GPT Engineer CLI',
  'Генерация полной кодовой базы из prompt файла. Vision-capable prompts.',
  'cli',
  ARRAY['CLI', 'Open Source', 'Generator'],
  'https://github.com/AntonOsika/gpt-engineer',
  'Бесплатно',
  'free',
  ARRAY['Prompt → full codebase', 'Clarification questions', 'Improve existing code', 'Vision support'],
  'GPT-4, Claude, Azure, локальные',
  true,
  'Начинающий / Средний'
),
(
  'mentat',
  'Mentat',
  'CLI AI Coding Assistant. Multi-file editing, project-wide context.',
  'cli',
  ARRAY['CLI', 'Open Source', 'Multi-file'],
  'https://github.com/AbanteAI/mentat',
  'Бесплатно',
  'free',
  ARRAY['Multi-file editing', 'Project-wide context', 'Git integration', 'Понимание новых кодовых баз'],
  'GPT-4',
  true,
  'Средний'
),
(
  'sweep',
  'Sweep AI',
  'AI Junior Developer. Автоматические PR из GitHub issues, next-edit autocomplete.',
  'cli',
  ARRAY['GitHub', 'Agent', 'JetBrains'],
  'https://sweep.dev',
  'Freemium',
  'freemium',
  ARRAY['PR из GitHub issues', 'Next-edit autocomplete', 'Bug fixes', 'JetBrains интеграция'],
  'Собственные модели',
  false,
  'Средний'
),

-- === UI/DESIGN TOOLS ===
(
  'galileo',
  'Galileo AI',
  'AI UI Generator. Text-to-UI, Image-to-UI, high-fidelity Figma export.',
  'ui',
  ARRAY['UI', 'Figma', 'Design'],
  'https://galileo.ai',
  'Freemium',
  'freemium',
  ARRAY['Text-to-UI', 'Image-to-UI', 'Figma export', 'Standard/Experimental modes'],
  'Gemini 2.5 Flash/Pro',
  false,
  'Начинающий'
),
(
  'uizard',
  'Uizard',
  'AI UI/Prototyping. Autodesigner 2.0, screenshot/sketch scanners, CSS/React export.',
  'ui',
  ARRAY['UI', 'Prototyping', 'Sketch-to-code'],
  'https://uizard.io',
  '$12/мес Pro',
  'freemium',
  ARRAY['Autodesigner 2.0', 'Screenshot/sketch scanners', 'Multi-screen prototypes', 'CSS/React export'],
  'Autodesigner 2.0',
  false,
  'Начинающий'
),
(
  'framer',
  'Framer AI',
  'AI Website Builder. Wireframer (chat to layout), Workshop (AI components).',
  'ui',
  ARRAY['Website', 'No-code', 'Design'],
  'https://framer.com',
  '$10/мес Basic',
  'freemium',
  ARRAY['Wireframer chat to layout', 'Workshop AI components', 'AI Translate', 'AI Plugins (GPT, Claude, Gemini)'],
  'Собственные + GPT, Claude, Gemini',
  false,
  'Начинающий / Средний'
),
(
  'builder',
  'Builder.io',
  'Visual Development Platform + CMS. AI design-to-code, A/B testing, Figma plugin.',
  'ui',
  ARRAY['CMS', 'Design-to-code', 'Multi-framework'],
  'https://builder.io',
  '$19/мес Pro',
  'freemium',
  ARRAY['AI design-to-code', 'Visual editor + Headless CMS', 'React, Vue, Angular, Qwik', 'A/B testing'],
  'Собственные модели',
  false,
  'Средний'
),
(
  'locofy',
  'Locofy',
  'Design-to-Code AI. Large Design Models, React/Vue/Flutter export, Storybook.',
  'ui',
  ARRAY['Figma', 'Design-to-code', 'Multi-framework'],
  'https://locofy.ai',
  '$24/мес Pro',
  'freemium',
  ARRAY['Large Design Models (LDMs)', 'Lightning быстрая конверсия', 'React, Vue, Flutter export', 'Storybook интеграция'],
  'Large Design Models',
  false,
  'Средний'
),
(
  'anima',
  'Anima',
  'Figma to React/Vue/HTML. Anima Playground для vibe-coding, one-click deploy.',
  'ui',
  ARRAY['Figma', 'React', 'Playground'],
  'https://animaapp.com',
  '$15/мес Pro',
  'freemium',
  ARRAY['Anima Playground vibe-coding', 'Figma to React/Vue/HTML', 'AI agent для логики', 'One-click deploy'],
  'Claude Sonnet 3.7, GPT o3-mini',
  false,
  'Начинающий / Средний'
),

-- === MOBILE ===
(
  'flutterflow',
  'FlutterFlow',
  'No-Code/Low-Code Mobile Builder. Drag-and-drop, full Flutter code export.',
  'mobile',
  ARRAY['Flutter', 'No-code', 'Mobile'],
  'https://flutterflow.io',
  '$30/мес Standard',
  'freemium',
  ARRAY['Drag-and-drop builder', 'Full Flutter code export', 'Firebase/Supabase интеграция', 'One-click publish'],
  'AI Assistant',
  false,
  'Начинающий / Средний'
),
(
  'draftbit',
  'Draftbit',
  'Low-Code Mobile Builder. Full React Native code export, real-time preview.',
  'mobile',
  ARRAY['React Native', 'Low-code', 'Mobile'],
  'https://draftbit.com',
  '$19/мес Basic',
  'freemium',
  ARRAY['Full React Native export', 'Real-time preview', 'Reusable Blocks', 'REST API интеграции'],
  'AI assistance',
  false,
  'Средний'
),
(
  'bravo',
  'Bravo Studio',
  'Design-First Mobile Builder. Figma to native iOS/Android apps.',
  'mobile',
  ARRAY['Figma', 'Native', 'Mobile'],
  'https://bravostudio.app',
  '$22/мес Solo',
  'freemium',
  ARRAY['Figma to native apps', 'Swift/Kotlin compiled', 'REST API integration', 'AI workflows'],
  'AI workflows',
  false,
  'Начинающий / Средний'
),

-- === AI AGENTS ===
(
  'devin',
  'Devin',
  'Autonomous AI Software Engineer от Cognition Labs. End-to-end: issue → PR.',
  'agent',
  ARRAY['Agent', 'Autonomous', 'Enterprise'],
  'https://devin.ai',
  'От $20 + ACU',
  'paid',
  ARRAY['Полностью автономная разработка', 'Planning & execution', 'Devin IDE, Wiki', 'Jira/Slack интеграция'],
  'SWE-1.5',
  false,
  'Продвинутый'
),
(
  'swe-agent',
  'SWE-Agent',
  'Open Source AI Agent для GitHub Issues. SOTA на SWE-bench.',
  'agent',
  ARRAY['Agent', 'Open Source', 'Research'],
  'https://swe-agent.com',
  'Бесплатно',
  'free',
  ARRAY['GitHub issues → fixes', 'SOTA на SWE-bench', 'Sandboxed execution', 'CTF solving, web tasks'],
  'GPT-4o, Claude Sonnet 4',
  true,
  'Продвинутый'
),

-- === ASSISTANTS ===
(
  'phind',
  'Phind',
  'AI Search + Coding Assistant. Real-time web search, VS Code интеграция.',
  'assistant',
  ARRAY['Search', 'VS Code', 'Documentation'],
  'https://phind.com',
  '$15/мес Plus',
  'freemium',
  ARRAY['AI-powered code search', 'Real-time web search', 'VS Code интеграция', 'Python code execution'],
  'Phind-70B, GPT-4',
  false,
  'Начинающий / Средний'
),
(
  'claude',
  'Claude',
  'AI от Anthropic. 200K токенов контекста, Artifacts для кода, лидер в бенчмарках.',
  'assistant',
  ARRAY['LLM', 'Anthropic', '200K context'],
  'https://claude.ai',
  '$20/мес Pro',
  'freemium',
  ARRAY['200K токенов контекста', 'Artifacts для кода', 'Projects для организации', 'Лидер в coding бенчмарках'],
  'Claude 4.1 Opus, Sonnet 4.5',
  false,
  'Начинающий / Средний / Продвинутый'
),
(
  'chatgpt',
  'ChatGPT',
  'Универсальный AI от OpenAI. Canvas для кода, Code Interpreter, GPT-4o.',
  'assistant',
  ARRAY['LLM', 'OpenAI', 'Canvas'],
  'https://chat.openai.com',
  '$20/мес Plus',
  'freemium',
  ARRAY['Canvas для редактирования кода', 'Code Interpreter', 'GPT-4o мультимодальность', 'Custom GPTs'],
  'GPT-4o, GPT-4 Turbo, o1',
  false,
  'Начинающий / Средний / Продвинутый'
),
(
  'supabase-ai',
  'Supabase AI',
  'Backend-as-a-Service + AI. AI Assistant для Postgres, pgvector для RAG.',
  'assistant',
  ARRAY['Backend', 'Postgres', 'RAG'],
  'https://supabase.com',
  'Freemium',
  'freemium',
  ARRAY['AI Assistant для SQL', 'pgvector для embeddings', 'Edge Functions', 'Default backend для v0, Bolt, Lovable'],
  'AI Assistant',
  true,
  'Средний / Продвинутый'
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  tags = EXCLUDED.tags,
  url = EXCLUDED.url,
  pricing = EXCLUDED.pricing,
  pricing_type = EXCLUDED.pricing_type,
  features = EXCLUDED.features,
  llm = EXCLUDED.llm,
  open_source = EXCLUDED.open_source,
  level = EXCLUDED.level;

